name: CD

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

env:
  REGISTRY: ghcr.io
  IMAGE_BACKEND: ${{ github.repository }}-backend
  IMAGE_FRONTEND: ${{ github.repository }}-frontend

jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Login GHCR
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build & push backend
        run: |
          docker build -f hackathon/Dockerfile hackathon -t $REGISTRY/${IMAGE_BACKEND}:$GITHUB_SHA
          docker push $REGISTRY/${IMAGE_BACKEND}:$GITHUB_SHA

      - name: Build & push frontend
        run: |
          docker build -f packages/twenty-front/Dockerfile packages/twenty-front -t $REGISTRY/${IMAGE_FRONTEND}:$GITHUB_SHA
          docker push $REGISTRY/${IMAGE_FRONTEND}:$GITHUB_SHA
